services:
  web:
    image: nginx
    ports:
      - "8080:80"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
   
    environment:
     AMBIENTE: ${AMBIENTE}  

volumes:
  redis-data:
   